version: "3"
services:
  nginx:
    container_name: nginx
    image: a273218159/nginx:1.15.3
    restart: always
    tty: true
    ports:
      - 80:80
      - 443:443
      - 1935:1935
    volumes:
      - /etc/localtime:/etc/localtime
    networks:
      - network1

  wordpress:
    container_name: wordpress
    image: wordpress
    restart: always
    tty: true
    environment:
      - WORDPRESS_DB_HOST=mariadb
      - WORDPRESS_DB_PASSWORD=
    depends_on:
      - mariadb
    volumes:
      - /etc/localtime:/etc/localtime
      - ./wordpress/:/var/www/html/wp-content/
    networks:
      - network1

  zentao:
    container_name: zentao
    restart: always
    tty: true
    image: a273218159/zentao:10.3.1
    volumes:
      - /etc/localtime:/etc/localtime
    ports:
      - 70:80
    networks:
      - network1

  svn:
    container_name: svn
    restart: always
    image: a273218159/svn
    volumes:
      - /etc/localtime:/etc/localtime
    ports:
      - 71:80
    networks:
      - network1
      

  jenkins:
    container_name: jenkins
    restart: always
    image: a273218159/jenkins
    environment:
      - JENKINS_OPTS="--prefix=/jenkins"
      - JAVA_OPTS="-Duser.timezone=Asia/Shanghai"
    volumes:
      - /etc/localtime:/etc/localtime
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/bin/docker:/usr/bin/docker
      - /usr/local/bin/docker-compose:/usr/local/bin/docker-compose
      - /usr/lib64/libltdl.so.7:/usr/lib/x86_64-linux-gnu/libltdl.so.7
    ports:
      - 72:8080
    networks:
      - network1

  #可通过以下命令开启慢查询，直接通过command命令指定无效
  #sed -i 's/#log_min_duration_statement = -1/log_min_duration_statement = 100/g' /var/lib/postgresql/data/postgresql.conf
  #可通过crontab -e设置定时任务定时备份数据库，以下命令为每天早晨2点备份postgres数据库(需要先创建backup文件夹，可能需要先安装vim命令)：
  #echo '#!/bin/bash'>/pg_dump.sh
  #echo 'pg_dump -U postgres -w -d postgres -f /var/lib/postgresql/data/backup/postgres.$(date "+%Y%m%d%H%M%S").sql'>>/pg_dump.sh
  #* 2 * * * /pg_dump.sh
  #可通过以下命令还原数据库(需要先创建数据库)：
  #psql -U postgres -w -d postgres -f /var/lib/postgresql/data/backup/postgres.?.sql
  pgsql:
    container_name: pgsql9.6
    restart: always
    image: postgres:9.6
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: 123456
    volumes:
      - /etc/localtime:/etc/localtime
      - ./pgsql9.6:/var/lib/postgresql/data
    networks:
      - network1

  mariadb:
    container_name: mariadb
    restart: always
    image: mariadb:latest
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - /etc/localtime:/etc/localtime
      - ./mariadb:/var/lib/mysql
    networks:
      - network1

  phabricator:
    container_name: phabricator
    restart: always
    image: bitnami/phabricator:latest
    depends_on:
      - mariadb
    environment:
      - MARIADB_HOST:mariadb
      - PHABRICATOR_HOST=phabricator.{domain}
      - PHABRICATOR_USERNAME=admin
      - PHABRICATOR_PASSWORD=123456
      - PHABRICATOR_EMAIL=273218159@qq.com
    volumes:
      - /etc/localtime:/etc/localtime
      - ./phabricator:/bitnami
    networks:
      - network1

networks:
  network1:
