FROM jenkins/jenkins:lts

USER root

RUN echo deb http://mirrors.aliyun.com/debian stretch main contrib non-free \
	deb http://mirrors.aliyun.com/debian stretch-proposed-updates main contrib non-free \
	deb http://mirrors.aliyun.com/debian stretch-updates main contrib non-free \
	deb-src http://mirrors.aliyun.com/debian stretch main contrib non-free \
	deb-src http://mirrors.aliyun.com/debian stretch-proposed-updates main contrib non-free \
	deb-src http://mirrors.aliyun.com/debian stretch-updates main contrib non-free \
	deb http://mirrors.aliyun.com/debian-security/ stretch/updates main non-free contrib \
	deb-src http://mirrors.aliyun.com/debian-security/ stretch/updates main non-free contrib \
    > /etc/apt/sources.list \
    && apt-get update \
    && apt-get install -y libltdl-dev
